# Generated by Django 3.2.8 on 2021-10-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0002_auto_20211012_1206'),
        ('eshop_products', '0002_auto_20211010_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_product_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
