# Generated by Django 3.2.8 on 2021-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ی ما'),
        ),
    ]
