# Generated by Django 3.2.8 on 2021-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_sitesettings_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copy_rights',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
